# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 42d74423f6ce954f683757d62e9bb38b6cd14c1bba7372e43ae3348102e2f66267e53d98f1a2e1edc6f92e1073c703b86b78c8252630462d4cea99c172e16d0b

test:
  secret_key_base: c02a807d2ef9d37c0e4d66282772bed4e3ac42836cd8e0c9a100ec3869026cc9fba799d0885cf8ecb52675f8ab584102f8ea5e33296acd2a0cbf561954568676

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
